"""Load Falaq Nashr's real catalogue into the `books` table.

Replaces whatever is in the `books` table (any sample/old data) with the real
titles in ``scripts/books_seed.json`` — the 54 active books across Falaq
Nashr's imprints (Nun nashr, Falaq nashr, Eng sharafli ummat, Holis nashr,
G‘iyosiddin Habibulloh). Prices are intentionally omitted — the AI assistant
never quotes prices to customers.

The seed file is generated by research + editing; each entry may carry a
``image`` filename that must exist under ``book_images/`` to be sent to users.

Usage (inside the container, which has DB access):
    python -m scripts.import_books
"""

import asyncio
import json
from pathlib import Path

from sqlalchemy import text

from bot.database import engine, session_factory
from bot.models import Base, Book

SEED_PATH = Path(__file__).resolve().parent / "books_seed.json"

# Book columns we allow the seed file to set.
_FIELDS = {
    "title", "author", "publisher", "genre", "annotation",
    "language", "age_group", "isbn", "year", "pages", "tags", "image",
}


def _load_seed() -> list[dict]:
    with SEED_PATH.open(encoding="utf-8") as f:
        rows = json.load(f)
    books: list[dict] = []
    for r in rows:
        b = {k: v for k, v in r.items() if k in _FIELDS and v not in (None, "")}
        if not b.get("title"):
            continue
        books.append(b)
    return books


async def main() -> None:
    books = _load_seed()

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
        # create_all never ALTERs an existing table — make sure newer columns
        # exist on catalogues created before they were added.
        await conn.execute(
            text("ALTER TABLE books ADD COLUMN IF NOT EXISTS image VARCHAR(255)")
        )
        await conn.execute(
            text("ALTER TABLE books ADD COLUMN IF NOT EXISTS publisher VARCHAR(120)")
        )
        # Remove whatever is there now (old catalogue) before loading the real books.
        await conn.execute(text("DELETE FROM books"))

    async with session_factory() as session:
        session.add_all([Book(**b) for b in books])
        await session.commit()

    await engine.dispose()

    with_img = sum(1 for b in books if b.get("image"))
    print(f"Imported {len(books)} real books (old catalogue removed).")
    print(f"  {with_img} have a cover image, {len(books) - with_img} do not.")


if __name__ == "__main__":
    asyncio.run(main())
